/**
 * Renders every view against the REAL staged artifacts and asserts that
 * B14's five gate fields actually reach the output.
 *
 *     npm run render-check
 *
 * Why this exists rather than a screenshot. `tsc` proves the code compiles
 * and `vite build` proves it bundles; neither proves it renders. The failure
 * this catches is a field that type-checks against the interface but is
 * absent, null, or a different shape in the artifact the sweep actually
 * wrote -- which is the realistic way this dashboard breaks, because the
 * artifacts are regenerated by a separate Python pipeline that knows nothing
 * about these types.
 *
 * renderToString needs no DOM, so this runs in plain node with no browser.
 * It renders ALL 200 drill-downs, not a sample: the interesting mandates are
 * the odd ones -- the empty conformal set, the post-terminal re-solve, the
 * opt-out with no debit, the mandate that spent no slot at all -- and a
 * spot-check would miss exactly those.
 *
 * The gate says the drill-down must show belief, chosen slot, binding
 * constraint, conformal set and ledger trail. This file is where that claim
 * is checked by machine instead of asserted in a commit message.
 */
import { renderToString } from "react-dom/server";
import fs from "node:fs";
import Merchant from "./src/Merchant";
import Acquirer from "./src/Acquirer";
import Drilldown from "./src/Drilldown";

const base = "public/data/";
const R = JSON.parse(fs.readFileSync(base + "results.json", "utf8"));
const G = JSON.parse(fs.readFileSync(base + "regimes.json", "utf8"));
const M = JSON.parse(fs.readFileSync(base + "mandates.json", "utf8"));

const merchant = renderToString(<Merchant results={R} mandates={M.mandates} />);
const acquirer = renderToString(<Acquirer regimes={G} />);
let drills = 0;
for (const m of M.mandates) { renderToString(<Drilldown m={m} />); drills++; }

const need = (hay: string, s: string, label: string) => {
  if (!hay.includes(s)) { console.log("MISSING in " + label + ": " + s); process.exitCode = 1; }
};
// The third bar -- the one the incumbent never reports -- must be on screen.
need(merchant, "Customers still subscribed", "merchant");
need(merchant, R.mandates_preserved, "merchant");
need(merchant, R.recovered, "merchant");
// The model-free reference arm must stay on the chart. Asserted by its
// on-screen label, which is now plain language rather than the internal
// policy name -- the point of the check is that the arm the engine LOSES to
// is visible, not what it is called in the code.
need(merchant, "Try once, then stop", "merchant");
need(acquirer, "conformal gate", "acquirer");
need(acquirer, "above AFA", "acquirer");
const withLedger = M.mandates.find((x: any) => x.ledger.length);
const d = renderToString(<Drilldown m={withLedger} />);
for (const s of ["conformal set", "binding constraint", "ledger trail", "slot ", "idempotency key"])
  need(d, s, "drilldown");
console.log("rendered: merchant " + merchant.length + " chars, acquirer " + acquirer.length +
            " chars, " + drills + " drill-downs, no exceptions");
